use-grammars = { only = [ "go", "rust", "python", "typescript", "yaml", "dockerfile", "markdown", "git-rebase", "git-commit" ] }

[language-server.gopls]
command = "gopls"
config = { "gofumpt" = true, "local" = "goimports", "semanticTokens" = true, "staticcheck" = true, "verboseOutput" = true, "analyses" = { "fieldalignment" = true, "nilness" = true, unusedparams = true, unusedwrite = true, useany = true }, usePlaceholders = true, completeUnimported = true, hints = { "assignVariableType" = true, "compositeLiteralFields" = true, "compositeLiteralTypes" = true, "constantValues" = true, "functionTypeParameters" = true, "parameterNames" = true, "rangeVariableTypes" = true } }

[[language]]
name = "python"
auto-format = true
formatter = { command = "black" , args = ["-", "--quiet"] }

[[language]]
name = "go"
roots = ["go.work", "go.mod"]
auto-format = true
comment-token = "//"
language-servers = [ "gopls"]

[[language]]
name = "rust"
roots = ["Cargo.toml", "Cargo.lock"]
auto-format = true
language-servers = ["rust-analyzer"]
indent = { tab-width = 4, unit = "    " }

[language.debugger]
name = "rust-lldb"
transport = "stdio"
command = "rust-lldb"

[[language.debugger.templates]]
name = "binary"
request = "launch"

[[language.debugger.templates.completion]]
completion = "filename"
name = "binary"

[language.debugger.templates.args]
program = "{0}"
runInTerminal = false

[language-server.rust-analyzer.config]
check.command = "clippy"

[[language]]
name = "typescript"
auto-format = true

[[language]]
name = "markdown"
auto-format = true
