use-grammars = { only = [ "rust", "python", "typescript", "yaml", "dockerfile", "markdown", "git-rebase", "git-commit" ] }

[[language]]
name = "python"
auto-format = true
formatter = { command = "black" , args = ["-", "--quiet"] }

[[language]]
name = "rust"
roots = ["Cargo.toml", "Cargo.lock"]
auto-format = true
language-server = { command = "rust-analyzer" }
indent = { tab-width = 4, unit = "    " }

[language.config]
checkOnSave = { command = "clippy" }

[[language]]
name = "typescript"
auto-format = true

[[language]]
name = "markdown"
auto-format = true