import = [
  "~/.config/alacritty/catppuccin-mocha.toml",
  "~/.config/alacritty/keybindings.toml",
]

[shell]
args = ["-l", "-c", "zellij attach --index 0 || zellij"]
program = "/bin/zsh"

[env]
TERM = "xterm-256color"

[window]
decorations = "Buttonless"
padding = { x = 20, y = 20 }
opacity = 0.9
blur = true
option_as_alt = "Both"

[font]
size = 12
normal.family = "JetBrainsMono Nerd Font Mono"
