format = """
$cmd_duration\
$sudo\
$character\
"""

right_format = """
$directory\
$git_branch\
$time\
"""

add_newline = false

[character]
format = "$symbol "
success_symbol = "[◉](bold bright-purple)"
error_symbol = "[⊘](bright-purple)"

[sudo]
format = "[$symbol]($style)"
style = "bright-purple"
symbol = "◇┈"
disabled = false

[directory]
truncation_length = 2
truncation_symbol = "…/"
style = "italic dimmed white"
format = ' [$path]($style)[$read_only]($read_only_style)'

[cmd_duration]
min_time = 5000
format = "[$duration ](italic bright-yellow)"

[time]
disabled = false
format = "[ at $time]($style)"
time_format = "%R"
utc_time_offset = "local"
style = "dimmed white"

[git_branch]
format = "[$symbol $branch(:$remote_branch)]($style)"
symbol = "[](bold bright-purple)"
style = "bold italic bright-purple"
